package com.biblioteca.digital.model;

/**
 * ENUMERACION QUE DEFINE LAS CATEGORIAS DISPONIBLES PARA LOS LIBROS DEL SISTEMA
 *
 * ESTA ENUMERACION ESTABLECE LAS DIFERENTES CLASIFICACIONES TEMATICAS
 * QUE PUEDEN TENER LOS LIBROS EN EL CATALOGO DE LA BIBLIOTECA DIGITAL.
 * CADA CATEGORIA PERMITE ORGANIZAR Y FILTRAR EL CONTENIDO DE MANERA
 * EFICIENTE PARA FACILITAR LA BUSQUEDA Y NAVEGACION DE LOS USUARIOS.
 *
 * LAS CATEGORIAS CUBREN LOS PRINCIPALES GENEROS LITERARIOS Y AREAS
 * DE CONOCIMIENTO QUE NORMALMENTE SE ENCUENTRAN EN UNA BIBLIOTECA.
 *
 * @author MARIO FLORES
 * @version 1.0
 * @since 2025-05-26
 *
 * @see Book
 */
public enum BookCategory {

    /**
     * LITERATURA DE FICCION
     *
     * INCLUYE NOVELAS, CUENTOS Y OTRAS OBRAS DE FICCION LITERARIA.
     * NARRATIVAS IMAGINARIAS QUE EXPLORAN LA CONDICION HUMANA
     * A TRAVES DE HISTORIAS CREADAS POR EL AUTOR.
     */
    FICTION("Ficción"),

    /**
     * LITERATURA DE NO FICCION
     *
     * OBRAS BASADAS EN HECHOS REALES, BIOGRAFIAS, ENSAYOS, MEMORIAS
     * Y OTROS TEXTOS QUE NARRAN O ANALIZAN LA REALIDAD SIN ELEMENTOS
     * IMAGINARIOS O FICTICIOS.
     */
    NON_FICTION("No Ficción"),

    /**
     * MISTERIO Y NOVELA POLICIACA
     *
     * GENERO QUE SE CENTRA EN LA RESOLUCION DE CRIMENES, ENIGMAS
     * O SITUACIONES MISTERIOSAS. INCLUYE NOVELAS POLICIACAS,
     * THRILLERS Y LITERATURA DE SUSPENSE.
     */
    MYSTERY("Misterio"),

    /**
     * CIENCIA FICCION
     *
     * LITERATURA QUE EXPLORA ESCENARIOS FUTURISTICOS, TECNOLOGIAS
     * AVANZADAS, VIAJES ESPACIALES Y CONCEPTOS CIENTIFICOS
     * ESPECULATIVOS EN CONTEXTOS NARRATIVOS.
     */
    SCIENCE_FICTION("Ciencia Ficción"),

    /**
     * LITERATURA FANTASTICA
     *
     * GENERO QUE INCORPORA ELEMENTOS MAGICOS, SOBRENATURALES
     * O MITOLOGICOS EN MUNDOS IMAGINARIOS O ALTERNATIVOS.
     * INCLUYE FANTASIA EPICA, URBANA Y CONTEMPORANEA.
     */
    FANTASY("Fantasía"),

    /**
     * LITERATURA ROMANTICA
     *
     * OBRAS CENTRADAS EN RELACIONES AMOROSAS Y EMOCIONALES.
     * EXPLORA TEMAS DE AMOR, PASION Y RELACIONES INTERPERSONALES
     * COMO EJE PRINCIPAL DE LA NARRATIVA.
     */
    ROMANCE("Romance"),

    /**
     * LITERATURA DE TERROR Y HORROR
     *
     * GENERO DISEÑADO PARA PROVOCAR MIEDO, SUSPENSO Y TENSION.
     * INCLUYE NARRATIVAS SOBRENATURALES, PSICOLOGICAS Y
     * SITUACIONES PERTURBADORAS O AMENAZANTES.
     */
    HORROR("Terror"),

    /**
     * BIOGRAFIA Y AUTOBIOGRAFIA
     *
     * RELATOS DE VIDAS REALES DE PERSONAS SIGNIFICATIVAS.
     * INCLUYE BIOGRAFIAS AUTORIZADAS, MEMORIAS PERSONALES
     * Y NARRATIVAS DE EXPERIENCIAS VITALES.
     */
    BIOGRAPHY("Biografía"),

    /**
     * LIBROS DE HISTORIA
     *
     * OBRAS QUE ESTUDIAN Y NARRAN EVENTOS DEL PASADO.
     * INCLUYE HISTORIA MUNDIAL, LOCAL, POLITICA, SOCIAL
     * Y CULTURAL EN DIFERENTES PERIODOS TEMPORALES.
     */
    HISTORY("Historia"),

    /**
     * TEXTOS CIENTIFICOS Y TECNICOS
     *
     * LITERATURA ESPECIALIZADA EN CIENCIAS NATURALES, EXACTAS
     * Y APLICADAS. INCLUYE MANUALES TECNICOS, INVESTIGACIONES
     * Y DIVULGACION CIENTIFICA.
     */
    SCIENCE("Ciencia"),

    /**
     * LIBROS DE TECNOLOGIA E INFORMATICA
     *
     * MANUALES, GUIAS Y TEXTOS SOBRE TECNOLOGIAS DE LA INFORMACION,
     * PROGRAMACION, SISTEMAS Y AVANCES TECNOLOGICOS CONTEMPORANEOS.
     */
    TECHNOLOGY("Tecnología"),

    /**
     * LITERATURA DE AUTOAYUDA Y DESARROLLO PERSONAL
     *
     * LIBROS ORIENTADOS AL CRECIMIENTO PERSONAL, MOTIVACION,
     * MEJORA DE HABILIDADES Y DESARROLLO DE COMPETENCIAS
     * PARA LA VIDA PERSONAL Y PROFESIONAL.
     */
    SELF_HELP("Autoayuda"),

    /**
     * LIBROS DE COCINA Y GASTRONOMIA
     *
     * RECETARIOS, GUIAS CULINARIAS Y TEXTOS SOBRE GASTRONOMIA.
     * INCLUYE COCINA TRADICIONAL, INTERNACIONAL Y ESPECIALIZADA.
     */
    COOKING("Cocina"),

    /**
     * LITERATURA DE VIAJES
     *
     * GUIAS DE VIAJE, RELATOS DE EXPLORACION Y NARRATIVAS
     * SOBRE DESTINOS, CULTURAS Y EXPERIENCIAS DE VIAJEROS.
     */
    TRAVEL("Viajes"),

    /**
     * ARTE Y CULTURA
     *
     * LIBROS SOBRE HISTORIA DEL ARTE, CRITICA ARTISTICA,
     * CULTURA VISUAL Y MANIFESTACIONES ARTISTICAS EN
     * DIFERENTES MEDIOS Y PERIODOS.
     */
    ART("Arte"),

    /**
     * MUSICA Y ESPECTACULOS
     *
     * TEXTOS SOBRE TEORIA MUSICAL, HISTORIA DE LA MUSICA,
     * BIOGRAFIAS DE MUSICOS Y ANALISIS DE GENEROS MUSICALES.
     */
    MUSIC("Música"),

    /**
     * DEPORTES Y ACTIVIDAD FISICA
     *
     * MANUALES DE ENTRENAMIENTO, HISTORIA DEL DEPORTE,
     * BIOGRAFIAS DE DEPORTISTAS Y GUIAS DE ACTIVIDAD FISICA.
     */
    SPORTS("Deportes"),

    /**
     * SALUD Y MEDICINA
     *
     * TEXTOS SOBRE MEDICINA, SALUD PUBLICA, ANATOMIA,
     * NUTRICION Y CUIDADO PERSONAL DESDE PERSPECTIVA MEDICA.
     */
    HEALTH("Salud"),

    /**
     * EDUCACION Y PEDAGOGIA
     *
     * LIBROS SOBRE METODOLOGIAS EDUCATIVAS, PSICOLOGIA
     * DEL APRENDIZAJE Y RECURSOS PARA LA ENSEÑANZA.
     */
    EDUCATION("Educación"),

    /**
     * LITERATURA INFANTIL Y JUVENIL
     *
     * OBRAS DIRIGIDAS ESPECIFICAMENTE A PUBLICO MENOR DE EDAD.
     * INCLUYE CUENTOS, NOVELAS JUVENILES Y LITERATURA EDUCATIVA
     * ADAPTADA A DIFERENTES EDADES.
     */
    CHILDREN("Infantil"),

    /**
     * FILOSOFIA Y PENSAMIENTO
     *
     * TEXTOS FILOSOFICOS, ENSAYOS DE PENSAMIENTO Y REFLEXIONES
     * SOBRE TEMAS EXISTENCIALES, ETICOS Y METAFISICOS.
     */
    PHILOSOPHY("Filosofía"),

    /**
     * RELIGION Y ESPIRITUALIDAD
     *
     * TEXTOS RELIGIOSOS, ESTUDIOS TEOLOGICOS Y LITERATURA
     * ESPIRITUAL DE DIFERENTES TRADICIONES Y CREENCIAS.
     */
    RELIGION("Religión"),

    /**
     * ECONOMIA Y NEGOCIOS
     *
     * LIBROS SOBRE TEORIA ECONOMICA, GESTION EMPRESARIAL,
     * FINANZAS Y ESTRATEGIAS DE NEGOCIO.
     */
    BUSINESS("Negocios"),

    /**
     * POLITICA Y SOCIEDAD
     *
     * TEXTOS SOBRE SISTEMAS POLITICOS, ANALISIS SOCIAL,
     * POLITICAS PUBLICAS Y ESTRUCTURAS GUBERNAMENTALES.
     */
    POLITICS("Política"),

    /**
     * PSICOLOGIA Y COMPORTAMIENTO HUMANO
     *
     * ESTUDIOS SOBRE LA MENTE HUMANA, COMPORTAMIENTOS,
     * TERAPIAS PSICOLOGICAS Y ANALISIS DE LA CONDUCTA.
     */
    PSYCHOLOGY("Psicología"),

    /**
     * CATEGORIA GENERICA PARA OTROS TEMAS
     *
     * CLASIFICACION PARA LIBROS QUE NO ENCAJAN EN LAS CATEGORIAS
     * ANTERIORES O QUE ABARCAN TEMAS INTERDISCIPLINARIOS.
     */
    OTHER("Otros");

    /**
     * DESCRIPCION LEGIBLE DE LA CATEGORIA
     *
     * ALMACENO UNA DESCRIPCION EN TEXTO PLANO QUE SE PUEDE MOSTRAR
     * EN LA INTERFAZ DE USUARIO PARA MAYOR CLARIDAD Y COMPRENSION.
     */
    private final String description;

    /**
     * CONSTRUCTOR DEL ENUM BookCategory
     *
     * ESTABLEZCO LA DESCRIPCION ASOCIADA A CADA CATEGORIA PARA SU USO
     * EN INTERFACES DE USUARIO Y REPORTES DEL SISTEMA.
     *
     * @param description DESCRIPCION LEGIBLE DE LA CATEGORIA
     */
    BookCategory(String description) {
        this.description = description;
    }

    /**
     * OBTIENE LA DESCRIPCION LEGIBLE DE LA CATEGORIA
     *
     * @return DESCRIPCION DE LA CATEGORIA EN TEXTO PLANO
     */
    public String getDescription() {
        return description;
    }

    /**
     * VERIFICA SI LA CATEGORIA ES DE FICCION
     *
     * DETERMINO SI LA CATEGORIA CORRESPONDE A LITERATURA DE FICCION
     * PARA APLICAR FILTROS O CLASIFICACIONES ESPECIFICAS.
     *
     * @return TRUE SI ES CATEGORIA DE FICCION, FALSE EN CASO CONTRARIO
     */
    public boolean isFictionCategory() {
        return this == FICTION || this == MYSTERY || this == SCIENCE_FICTION ||
                this == FANTASY || this == ROMANCE || this == HORROR;
    }

    /**
     * VERIFICA SI LA CATEGORIA ES ACADEMICA O EDUCATIVA
     *
     * DETERMINO SI LA CATEGORIA CORRESPONDE A CONTENIDO ACADEMICO
     * PARA ORGANIZAR SECCIONES EDUCATIVAS DE LA BIBLIOTECA.
     *
     * @return TRUE SI ES CATEGORIA ACADEMICA, FALSE EN CASO CONTRARIO
     */
    public boolean isAcademicCategory() {
        return this == SCIENCE || this == TECHNOLOGY || this == HISTORY ||
                this == EDUCATION || this == PHILOSOPHY || this == PSYCHOLOGY;
    }

    /**
     * VERIFICA SI LA CATEGORIA ES PRACTICA O DE APLICACION
     *
     * DETERMINO SI LA CATEGORIA CORRESPONDE A CONOCIMIENTO APLICADO
     * O HABILIDADES PRACTICAS PARA LA VIDA COTIDIANA.
     *
     * @return TRUE SI ES CATEGORIA PRACTICA, FALSE EN CASO CONTRARIO
     */
    public boolean isPracticalCategory() {
        return this == SELF_HELP || this == COOKING || this == TRAVEL ||
                this == SPORTS || this == HEALTH || this == BUSINESS;
    }

    /**
     * VERIFICA SI LA CATEGORIA ES ADECUADA PARA MENORES
     *
     * DETERMINO SI EL CONTENIDO ES APROPIADO PARA PUBLICO INFANTIL
     * Y JUVENIL SEGUN LA CLASIFICACION DE LA CATEGORIA.
     *
     * @return TRUE SI ES APROPIADO PARA MENORES, FALSE EN CASO CONTRARIO
     */
    public boolean isChildFriendly() {
        return this == CHILDREN || this == EDUCATION || this == ART ||
                this == MUSIC || this == SPORTS || this == SCIENCE;
    }

    /**
     * OBTIENE TODAS LAS CATEGORIAS DISPONIBLES COMO ARRAY
     *
     * METODO UTILITARIO PARA OBTENER TODAS LAS CATEGORIAS DEL ENUM
     * PARA USO EN FORMULARIOS, FILTROS Y LISTADOS COMPLETOS.
     *
     * @return ARRAY CON TODOS LOS VALORES DEL ENUM
     */
    public static BookCategory[] getAllCategories() {
        return values();
    }

    /**
     * BUSCA UNA CATEGORIA POR SU DESCRIPCION
     *
     * LOCALIZO UNA CATEGORIA ESPECIFICA BASANDOME EN SU DESCRIPCION
     * TEXTUAL PARA FACILITAR BUSQUEDAS Y CONVERSIONES.
     *
     * @param description DESCRIPCION A BUSCAR
     * @return CATEGORIA CORRESPONDIENTE O NULL SI NO SE ENCUENTRA
     */
    public static BookCategory findByDescription(String description) {
        for (BookCategory category : values()) {
            if (category.getDescription().equalsIgnoreCase(description)) {
                return category;
            }
        }
        return null;
    }

    /**
     * OBTIENE LAS CATEGORIAS DE FICCION DISPONIBLES
     *
     * FILTRO Y RETORNO SOLO LAS CATEGORIAS QUE CORRESPONDEN
     * A LITERATURA DE FICCION PARA BUSQUEDAS ESPECIALIZADAS.
     *
     * @return ARRAY CON CATEGORIAS DE FICCION
     */
    public static BookCategory[] getFictionCategories() {
        return new BookCategory[]{
                FICTION, MYSTERY, SCIENCE_FICTION, FANTASY, ROMANCE, HORROR
        };
    }

    /**
     * OBTIENE LAS CATEGORIAS ACADEMICAS DISPONIBLES
     *
     * FILTRO Y RETORNO SOLO LAS CATEGORIAS DE CONTENIDO ACADEMICO
     * PARA ORGANIZACION DE SECCIONES EDUCATIVAS.
     *
     * @return ARRAY CON CATEGORIAS ACADEMICAS
     */
    public static BookCategory[] getAcademicCategories() {
        return new BookCategory[]{
                SCIENCE, TECHNOLOGY, HISTORY, EDUCATION, PHILOSOPHY, PSYCHOLOGY
        };
    }

    /**
     * OBTIENE LAS CATEGORIAS PRACTICAS DISPONIBLES
     *
     * FILTRO Y RETORNO SOLO LAS CATEGORIAS DE APLICACION PRACTICA
     * PARA SECCION DE LIBROS UTILITARIOS Y DE HABILIDADES.
     *
     * @return ARRAY CON CATEGORIAS PRACTICAS
     */
    public static BookCategory[] getPracticalCategories() {
        return new BookCategory[]{
                SELF_HELP, COOKING, TRAVEL, SPORTS, HEALTH, BUSINESS
        };
    }

    /**
     * CUENTA EL NUMERO TOTAL DE CATEGORIAS DISPONIBLES
     *
     * @return CANTIDAD TOTAL DE CATEGORIAS EN EL ENUM
     */
    public static int getTotalCategoriesCount() {
        return values().length;
    }

    /**
     * VERIFICA SI UNA CADENA CORRESPONDE A UNA CATEGORIA VALIDA
     *
     * VALIDO SI UN TEXTO DADO CORRESPONDE AL NOMBRE DE ALGUNA
     * CATEGORIA EXISTENTE EN EL ENUM.
     *
     * @param categoryName NOMBRE DE LA CATEGORIA A VERIFICAR
     * @return TRUE SI ES CATEGORIA VALIDA, FALSE EN CASO CONTRARIO
     */
    public static boolean isValidCategory(String categoryName) {
        if (categoryName == null || categoryName.trim().isEmpty()) {
            return false;
        }

        try {
            valueOf(categoryName.toUpperCase());
            return true;
        } catch (IllegalArgumentException e) {
            return false;
        }
    }

    /**
     * CONVIERTE UNA CADENA EN CATEGORIA ENUM
     *
     * METODO SEGURO PARA CONVERTIR UNA CADENA EN CATEGORIA
     * SIN LANZAR EXCEPCION SI LA CATEGORIA NO EXISTE.
     *
     * @param categoryName NOMBRE DE LA CATEGORIA
     * @return CATEGORIA CORRESPONDIENTE O OTHER SI NO SE ENCUENTRA
     */
    public static BookCategory fromString(String categoryName) {
        if (categoryName == null || categoryName.trim().isEmpty()) {
            return OTHER;
        }

        try {
            return valueOf(categoryName.toUpperCase());
        } catch (IllegalArgumentException e) {
            return OTHER;
        }
    }

    /**
     * OBTIENE UNA REPRESENTACION AMIGABLE DE LA CATEGORIA
     *
     * RETORNO LA DESCRIPCION LEGIBLE EN LUGAR DEL NOMBRE DEL ENUM
     * PARA MOSTRAR EN INTERFACES DE USUARIO.
     *
     * @return DESCRIPCION LEGIBLE DE LA CATEGORIA
     */
    @Override
    public String toString() {
        return description;
    }
}